package guru.springfamework.api.v1.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Created by jt on 10/6/17.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class VendorDTO {


    @ApiModelProperty(value = "This is the store/vendor name.", required = true)
    private String name;


    @ApiModelProperty(value = "This is the url of the vendor in the system", required = true,
            notes = "This value will be autogenerated and cannot be modified by the user.")
    @JsonProperty("vendor_url")
    private String vendorUrl;

}
